Name:           ros-kinetic-husky-bringup
Version:        0.3.0
Release:        0%{?dist}
Summary:        ROS husky_bringup package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/husky_bringup
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-husky-base
Requires:       ros-kinetic-husky-control
Requires:       ros-kinetic-husky-description
Requires:       ros-kinetic-imu-filter-madgwick
Requires:       ros-kinetic-imu-transformer
Requires:       ros-kinetic-lms1xx
Requires:       ros-kinetic-microstrain-3dmgx2-imu
Requires:       ros-kinetic-nmea-comms
Requires:       ros-kinetic-nmea-navsat-driver
Requires:       ros-kinetic-robot-localization
Requires:       ros-kinetic-robot-upstart
Requires:       ros-kinetic-tf
Requires:       ros-kinetic-tf2-ros
Requires:       ros-kinetic-um6
Requires:       ros-kinetic-um7
Requires:       scipy
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-roslaunch

%description
Clearpath Husky installation and integration package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Apr 11 2018 Paul Bovbel <paul@bovbel.com> - 0.3.0-0
- Autogenerated by Bloom

